#ifndef _ENUM_H
#define _ENUM_H

#define LENGTH 55

enum {
  N_CLOCK, N_PUTS, N_STRLEN, N_STRRCHR, N_STPCPY, N_STRSTR, N_GETENV,
  N_MALLOC, N_STRNCMP, N_MEMCHR, N_STRCMP, N_MEMSET, N_STRNCPY, N_MMAP,
  N_REALLOC, N_MEMMOVE, N_FREXP, N_MODF, N_POW, N_MEMCPY, N_FPUTC, N_MEMCMP,
  N_FREAD, N_GMTIME, N_FOPEN, N_FERROR, N_FCLOSE, N_REMOVE, N_MUNMAP, N_FREE,
  N_FWRITE, N_FFLUSH, N_SETJMP, N_PRINTF, N_VPRINTF, N_LONGJMP, N_FT_INIT,
  N_FT_NEWFACE, N_FT_SPS, N_FT_LC, N_FT_GCI, N_FT_LG, N_FT_RG, N_FT_GG,
  N_FT_GTB, N_FT_DG, N_PNG_CWS, N_PNG_CIS, N_PNG_II, N_PNG_WE, N_PNG_SI,
  N_PNG_SLF, N_PNG_SR, N_PNG_WP, N_PNG_DWS
};

#endif
